name: Android CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Copy CI gradle.properties
      run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties
    - name: Prepare build
      run: ./.buildscript/prepare_build.sh
    - name: Build with Gradle
      run: ./gradlew assembleDebug
    - name: Run ktlint
      run: ./gradlew spotlessCheck
    - name: Run unit test
      run: ./gradlew testDebugUnitTest
